name: lazarus IoC

on:
  push:
    paths:
      - '.github/workflows/manual.yml'  # 워크플로 파일이 수정되면 실행
  schedule:
    - cron: '15 */1 * * *'
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

jobs:
  collect-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: 리포지토리 체크아웃
      uses: actions/checkout@v3

    - name: Python 환경 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 의존성 패키지 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 비공개 저장소에서 파이썬 코드 가져오기
      run: |
        git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/NCITSSEC/lazarus_code.git --depth=1
        cp lazarus_code/lazarus-automation.py .
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

    - name: kimsuky IoC 데이터 수집 및 변환
      run: python lazarus-automation.py

    - name: 변경 사항 확인
      run: |
        git diff --quiet || echo "Changes detected"

    - name: 변경된 데이터 GitHub에 푸시
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/lazarus_IoC.txt
        git commit -m "자동 업데이트: lazarus IOC 데이터 갱신" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
